### ISSUE TITLE
todo from Dec 10 breakout group

### ISSUE THREAD

**Issue by derekeder** [datamade/searchable-map-template-turf#11]
* [x] note about or solution to weird template caching issue
* [x] note to delete all the custom filters to get your map to work, starting on line https://github.com/datamade/searchable-map-template-turf/blob/master/js/searchable_map_lib.js#L276
* [x] note about running a local web server on Windows / instructions on how to run a local web server
* [x] add notes about debugging javascript in the console
* [x] hard refresh is often required when debugging and loading new changes
* [x] the upper bound on points is around 1,000. at that volume the map becomes very slow
